src/Entity/Office.php
<?php

namespace AppBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="AppBundle\Repository\OfficeRepository")
 * @ORM\Table(
 *     name="office",
 *     uniqueConstraints={
 *         @ORM\UniqueConstraint(name="UNIQ_office_slug", columns="slug")
 *     },
 *     indexes={
 *         @ORM\Index(name="IDX_office_name", columns="name")
 *     }
 * )
 * @UniqueEntity(fields="slug")
 */
class Office implements PostAddressInterface, GeoPointInterface, \JsonSerializable
{
    use EntityIdentityTrait;
    use EntityCrudTrait;
    use EntityPostAddressTrait;
    use EntityGeoPointTrait;

    /**
     * @var string
     *
     * @Gedmo\Slug(fields={"name", "postAddress.zipCode"})
     * @ORM\Column(type="string")
     */
    private $slug;

    /**
     * @var string
     *
     * @ORM\Column(type="string")
     *
     * @Assert\NotBlank()
     */
    private $name;

    /**
     * @var User[]|Collection|iterable
     *
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\User", mappedBy="office")
     * @ORM\OrderBy({"lastName": "ASC", "firstName": "ASC"})
     */
    private $users;

    /**
     * @var OfficeCategory[]|Collection|iterable
     *
     * @ORM\ManyToMany(targetEntity="AppBundle\Entity\OfficeCategory", inversedBy="offices")
     * @ORM\OrderBy({"name": "ASC"})
     *
     * @Assert\Count(min="1", minMessage="Choose at least one category")
     */
    private $categories;

    public function __construct()
    {
        $this->postAddress = new PostAddressEmbeddable('UA', 'Mariupol');
        $this->coordinates = new GeoPointEmbeddable();
        $this->users = new ArrayCollection();
        $this->categories = new ArrayCollection();
    }

    public function jsonSerialize()
    {
        return [
            'id' => $this->id,
            'name' => $this->name,
            'fullName' => $this->getFullName(),
            'latitude' => $this->getLatitude(),
            'longitude' => $this->getLongitude(),
        ];
    }

    public function getFullName(): string
    {
        return
            "$this->name ({$this->getCountry()}, {$this->getCity()}" .
            (empty($this->getZipCode()) ? '' : ", {$this->getZipCode()}") .
            ')';
    }

    public function getFullAddress(): string
    {
        return $this->postAddress->getFullAddress();
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function getSlug(): string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getUsers()
    {
        return $this->users;
    }

    public function addUser(User $user): void
    {
        if (!$this->users->contains($user)) {
            $user->setOffice($this);
            $this->users[] = $user;
        }
    }

    public function removeUser(User $user): void
    {
        $user->setOffice(null);
        $this->users->removeElement($user);
    }

    public function addCategory(OfficeCategory $category): void
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
        }
    }

    public function removeCategory(OfficeCategory $category): void
    {
        $this->categories->removeElement($category);
    }
}

src/Entity/PostAddressInterface.php
<?php

namespace AppBundle\Entity;

interface PostAddressInterface
{
    public function getCountry(): string;

    public function getCity(): string;

    public function getAddress(): ?string;

    public function getZipCode(): ?string;
}

src/Controller/OfficeController.php
<?php

namespace AppBundle\Controller;

use AppBundle\Entity\Country;
use AppBundle\Entity\Office;
use AppBundle\Entity\User;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Entity;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

/**
 * @Route("/office")
 */
class OfficeController extends Controller
{
    /**
     * @Route("/", name="office_list")
     * @Method("GET")
     */
    public function officeListAction(Request $request)
    {
        return $this->render('office/list.html.twig', [
            'officePagination' => $this->get('knp_paginator')->paginate(
                $this->getDoctrine()->getRepository(Office::class)->createOfficesSortedQB(),
                $request->query->getInt('page', 1),
                5,
                ['defaultSortFieldName' => 'o.name', 'defaultSortDirection' => 'asc']
            )
        ]);
    }

    /**
     * @Route("/map", name="office_map")
     * @Method("GET")
     */
    public function officeMapAction()
    {
        $offices = $this->getDoctrine()->getRepository(Office::class)->findAll();

        return $this->render('office/map.html.twig', ['offices' => $offices]);
    }

    /**
     * @Route("/{slug}", name="office_view")
     *
     * @Method("GET")
     * @Entity("office", expr="repository.findOneBy({slug: slug})")
     */
    public function officeViewAction(Office $office)
    {
        $em = $this->getDoctrine();

        $officeCountry = $em->getRepository(Country::class)->findOneBy(['code' => $office->getCountry()]);
        $users = $em->getRepository(User::class)->findActiveUsersByOffice($office);

        return $this->render('office/view.html.twig', [
            'office' => $office,
            'officeCountry' => $officeCountry,
            'users' => $users,
        ]);
    }

    /**
     * @Route("/info_window/{id}", requirements={"id": "\d*"}, name="office_info_window")
     *
     * @Method("GET")
     * @Entity("office", expr="repository.find(id)")
     */
    public function officeInfoWindowAction(Office $office)
    {
        $em = $this->getDoctrine();

        $officeCountry = $em->getRepository(Country::class)->findOneBy(['code' => $office->getCountry()]);
        $users_count = $em->getRepository(User::class)->countActiveUsersByOffice($office);

        return $this->render('office/info_window.html.twig', [
            'office' => $office,
            'officeCountry' => $officeCountry,
            'users_count' => $users_count
        ]);
    }
}

templates/office/info_window.html.twig
<h4><a href="{{ path('office_view', {slug: office.slug}) }}" title="Office details">{{ office.name }}</a></h4>

<p><strong>Categories:</strong></p>
<ul>
    {% for category in office.categories %}
        <li>{{ category.name }}</li>
    {% endfor %}
</ul>

<address>
    <p>{{ officeCountry.name }}</p>
    <p>{{ office.fullAddress }}</p>
</address>

<p><em>Employees: {{ users_count }}</em></p>

templates/office/list.html.twig
{% extends 'base.html.twig' %}

{% block page_title 'Offices list' %}

{% block content %}
    {% if officePagination.totalItemCount > 0 %}
        <ul>
            {% for office in officePagination %}
                <li>
                    <a href="{{ path('office_view', {slug: office.slug}) }}"
                       title="View office">{{ office.fullName }}</a>
                </li>
            {% endfor %}
        </ul>

        {{ knp_pagination_render(officePagination) }}

        <div class="total">
            {{ officePagination.totalItemCount }} offices
        </div>
    {% else %}
        <em>No offices</em>
    {% endif %}
{% endblock %}

templates/office/map.html.twig
{% extends 'base.html.twig' %}

{% block page_title 'Offices map' %}

{% block content %}
    <div id="map"></div>
{% endblock %}

{% block stylesheets %}
    <style>
        #map {
            width: 100%;
            height: 600px;
        }
    </style>
{% endblock %}

{% block javascripts %}
    {% include 'shared/_google_map.html.twig' with {locations: offices, useInfoWindow: true, infoWindowRouteName: 'office_info_window'} %}
{% endblock %}

templates/office/view.html.twig
{% extends 'base.html.twig' %}

{% block page_title 'Office' %}

{% block content %}
    <div class="actions">
        <button class="btn btn-primary btn-back">Back</button>

        {% if is_granted('ROLE_ADMIN') %}
            <a href="{{ path('admin_office_edit', {id: office.id}) }}" class="btn btn-primary">Edit office</a>
        {% endif %}
    </div>

    <h4>{{ office.name }}</h4>

    <div class="row">
        <div class="col-sm-8">
            <p><strong>Categories:</strong></p>
            <ul>
                {% for category in office.categories %}
                    <li>{{ category.name }}</li>
                {% endfor %}
            </ul>

            <address>
                <p><strong>Country:</strong> {{ officeCountry.name }} ({{ office.country }})</p>
                <p><strong>City:</strong> {{ office.city }}</p>
                <p><strong>Address:</strong> {{ office.address }}</p>
                <p><strong>ZIP code:</strong> {{ office.zipCode }}</p>
            </address>

            {% if users is not empty %}
                <p><em>Employees:</em></p>
                <ul>
                    {% for user in users %}
                        <li>{{ user.fullNameReversed(', ') }}</li>
                    {% endfor %}
                </ul>
            {% else %}
                <p><em>No employees in this office</em></p>
            {% endif %}
        </div>
        <div class="col-sm-4">
            <div id="map"></div>
        </div>
    </div>
{% endblock %}

{% block stylesheets %}
    <style>
        #map {
            width: 300px;
            height: 300px;
        }
    </style>
{% endblock %}

{% block javascripts %}
    {% include 'shared/_google_map.html.twig' with {locations: [office]} %}
{% endblock %}