src/Entity/GeoPointInterface.php
<?php

namespace AppBundle\Entity;

interface GeoPointInterface
{
    public function getLongitude(): ?float;

    public function getLatitude(): ?float;
}

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block meta '' %}

    <title>
        {%- block title -%}
            {% block page_head_title %}{{ block('page_title') }}{% endblock %} | {% block app_title 'CS50_2017' %}
        {%- endblock -%}
    </title>

    <link rel="stylesheet" href="{{ asset('css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('css/bootstrap-theme.min.css') }}">
    <link rel="stylesheet" href="{{ asset('css/jquery.chosen.min.css') }}">
    {% block stylesheets '' %}
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">
    {% block final_stylesheets '' %}
</head>
<body>
{% block header %}
    <header>
        <div class="container">
            <div class="page-header">CS50_2017</div>
            {% include 'nav_main.html.twig' %}
        </div>
    </header>
{% endblock %}

<div class="container">
    {% for type, messages in app.flashes %}
        {% for message in messages %}
            <div class="alert alert-{{ type }} alert-dismissable fade in">
                <a href="#" class="close" data-dismiss="alert" aria-label="close" title="close">×</a>
                {{ message }}
            </div>
        {% endfor %}
    {% endfor %}

    <h1>{% block page_title '' %}</h1>

    <div class="content">
        {% block content '' %}
    </div>
</div>

{% block footer %}
    <footer>
        <div class="container">
            <div class="page-footer">
                &copy; {{ 'now'|date('Y') }}
            </div>
        </div>
    </footer>
{% endblock %}

<script src="{{ asset('js/jquery-3.2.1.min.js') }}"></script>
<script src="{{ asset('js/bootstrap-3.3.7.min.js') }}"></script>
<script src="{{ asset('js/eModal-1.2.65.min.js') }}"></script>
<script src="{{ asset('js/jquery.chosen-1.6.2.min.js') }}"></script>
{% block javascripts '' %}
<script type="text/javascript" src="{{ asset('js/app.js') }}"></script>
{% block final_javascripts '' %}

</body>
</html>

templates/form_theme.html.twig
{% use 'bootstrap_3_horizontal_layout.html.twig' %}

{% block geo_point_row %}
    <div class="form-group">
        {{ form_label(form.latitude, 'Latitude:') }}

        <div class="col-sm-4">
            {{ form_widget(form.latitude) }}
            {{ form_errors(form.latitude) }}
        </div>

        {{ form_label(form.longitude, 'Longitude:') }}

        <div class="col-sm-4">
            {{ form_widget(form.longitude) }}
            {{ form_errors(form.longitude) }}
        </div>
    </div>
{% endblock %}

templates/menu.html.twig
{% extends 'knp_menu.html.twig' %}

{% import 'knp_menu.html.twig' as macros %}

{% block item %}
    {% if item.displayed %}
        {%- set attributes = item.attributes %}
        {%- set is_dropdown = attributes.dropdown|default(false) %}
        {%- set divider_prepend = attributes.divider_prepend|default(false) %}
        {%- set divider_append = attributes.divider_append|default(false) %}

        {# unset bootstrap specific attributes #}
        {%- set attributes = attributes|merge({'dropdown': null, 'divider_prepend': null, 'divider_append': null }) %}

        {%- if divider_prepend %}
            {{ block('dividerElement') }}
        {%- endif %}

        {# building the class of the item #}
        {%- set classes = item.attribute('class') is not empty ? [item.attribute('class')] : [] %}
        {%- if matcher.isCurrent(item) %}
            {%- set classes = classes|merge([options.currentClass]) %}
        {%- elseif matcher.isAncestor(item, options.depth) %}
            {%- set classes = classes|merge([options.ancestorClass]) %}
        {%- endif %}
        {%- if item.actsLikeFirst %}
            {%- set classes = classes|merge([options.firstClass]) %}
        {%- endif %}
        {%- if item.actsLikeLast %}
            {%- set classes = classes|merge([options.lastClass]) %}
        {%- endif %}

        {# building the class of the children #}
        {%- set childrenClasses = item.childrenAttribute('class') is not empty ? [item.childrenAttribute('class')] : [] %}
        {%- set childrenClasses = childrenClasses|merge(['menu_level_' ~ item.level]) %}

        {# adding classes for dropdown #}
        {%- if is_dropdown %}
            {%- set classes = classes|merge(['dropdown']) %}
            {%- set childrenClasses = childrenClasses|merge(['dropdown-menu']) %}
        {%- endif %}

        {# putting classes together #}
        {%- if classes is not empty %}
            {%- set attributes = attributes|merge({'class': classes|join(' ')}) %}
        {%- endif %}
        {%- set listAttributes = item.childrenAttributes|merge({'class': childrenClasses|join(' ') }) %}

        {# displaying the item #}
        <li{{ macros.attributes(attributes) }}>
            {%- if is_dropdown %}
                {{ block('dropdownElement') }}
            {%- elseif item.uri is not empty and (not item.current or options.currentAsLink) %}
                {{ block('linkElement') }}
            {%- else %}
                {{ block('spanElement') }}
            {%- endif %}
            {# render the list of children#}
            {{ block('list') }}
        </li>

        {%- if divider_append %}
            {{ block('dividerElement') }}
        {%- endif %}
    {% endif %}
{% endblock %}

{% block dividerElement %}
    {% if item.level == 1 %}
        <li class="divider-vertical"></li>
    {% else %}
        <li class="divider"></li>
    {% endif %}
{% endblock %}

{% block linkElement %}
    <a href="{{ item.uri }}"{{ macros.attributes(item.linkAttributes) }}>
        {% if item.attribute('icon') is not empty %}
            <i class="{{ item.attribute('icon') }}"></i>
        {% endif %}
        {{ block('label') }}
    </a>
{% endblock %}

{% block spanElement %}
    <span>{{ macros.attributes(item.labelAttributes) }}>
        {% if item.attribute('icon') is not empty  %}
            <i class="{{ item.attribute('icon') }}"></i>
        {% endif %}
        {{ block('label') }}
	</span>
{% endblock %}

{% block dropdownElement %}
    {%- set classes = item.linkAttribute('class') is not empty ? [item.linkAttribute('class')] : [] %}
    {%- set classes = classes|merge(['dropdown-toggle']) %}
    {%- set attributes = item.linkAttributes %}
    {%- set attributes = attributes|merge({'class': classes|join(' ')}) %}
    {%- set attributes = attributes|merge({'data-toggle': 'dropdown'}) %}
    <a href="#"{{ macros.attributes(attributes) }}>
        {% if item.attribute('icon') is not empty  %}
            <i class="{{ item.attribute('icon') }}"></i>
        {% endif %}
        {{ block('label') }}
        <b class="caret"></b>
    </a>
{% endblock %}

{% block label %}{{ item.label|trans }}{% endblock %}

templates/nav_main.html.twig
{% spaceless %}
    <nav class="navbar navbar-default">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#navbar-main" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>

        <div class="collapse navbar-collapse" id="navbar-main">
            {% if app.user %}
                {% if is_granted('ROLE_USER') %}
                    {{ knp_menu_render('AppBundle:MenuBuilder:userMenu', {'currentClass': 'active'}) }}
                {% elseif is_granted('ROLE_ADMIN') %}
                    {{ knp_menu_render('AppBundle:MenuBuilder:adminMenu', {'currentClass': 'active'}) }}
                {% endif %}
            {% else %}
                {{ knp_menu_render('AppBundle:MenuBuilder:defaultMenu', {'currentClass': 'active'}) }}
            {% endif %}

            <ul class="nav navbar-nav navbar-right">
                <li class="login-state">
                    {% if app.user %}
                        Logged in as: <strong>{{ app.user.fullName }}</strong> <a href="{{ path('security_logout') }}">Logout</a>
                    {% else %}
                        Not logged in. <a href="{{ path('security_login') }}">Login</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </nav>
{% endspaceless %}