src/Entity/PostAddressInterface.php
<?php

namespace AppBundle\Entity;

interface PostAddressInterface
{
    public function getCountry(): string;

    public function getCity(): string;

    public function getAddress(): ?string;

    public function getZipCode(): ?string;
}

src/Entity/User.php
<?php

namespace AppBundle\Entity;

use AppBundle\Utils\Registration;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="AppBundle\Repository\UserRepository")
 * @ORM\Table(
 *     name="user",
 *     uniqueConstraints={
 *         @ORM\UniqueConstraint(name="UNIQ_user_email", columns="email")
 *     },
 *     indexes={
 *         @ORM\Index(name="IDX_user_full_name", columns={"last_name", "first_name"})
 *     }
 * )
 */
class User implements UserInterface, PostAddressInterface
{
    const ENABLED = 'enabled';
    const DISABLED = 'disabled';

    const ROLE_USER = 'user';
    const ROLE_ADMIN = 'admin';

    use EntityIdentityTrait;
    use EntityCrudTrait;
    use EntityPersonNameTrait;
    use EntityPostAddressTrait;
    use TimestampableEntity;

    /**
     * @ORM\Column(type="string")
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=6)
     */
    private $gender;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $birthdate;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=5, options={"default"=User::ROLE_USER})
     */
    private $role;

    /**
     * @ORM\Column(type="string", length=10, options={"default"=User::DISABLED})
     */
    private $status;

    /**
     * @ORM\Column(type="datetime")
     */
    private $registeredAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $activatedAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $lastLoggedAt;

    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Office", inversedBy="users")
     * @ORM\JoinColumn(onDelete="SET NULL")
     */
    private $office;

    public function __construct(
        string $email,
        string $firstName,
        string $lastName,
        string $gender,
        \DateTime $birthdate,
        string $password,
        string $role,
        string $status,
        PostAddressEmbeddable $postAddress,
        ?Office $office = null
    ) {
        $this->email = $email;
        $this->firstName = $firstName;
        $this->lastName = $lastName;
        $this->gender = $gender;
        $this->birthdate = $birthdate;
        $this->password = $password;
        $this->role = $role;
        $this->status = $status;
        $this->registeredAt = new \DateTime();
        $this->postAddress = $postAddress;
        $this->office = $office;
    }

    public function getRoles(): array
    {
        return ($this->role == self::ROLE_ADMIN) ? ['ROLE_ADMIN'] : ['ROLE_USER'];
    }

    public function getPassword(): string
    {
        return $this->password;
    }

    public function getSalt()
    {
    }

    public function getUsername(): string
    {
        return $this->email;
    }

    public function eraseCredentials(): void
    {
    }

    public function getEmail(): string
    {
        return $this->email;
    }

    public function getGender(): string
    {
        return $this->gender;
    }

    public function getBirthdate(): ?\DateTime
    {
        return $this->birthdate;
    }

    public function getAge(): int
    {
        return $this->birthdate ? ($this->birthdate->diff(new \DateTime()))->y : 0;
    }

    public function getRole(): string
    {
        return $this->role;
    }

    public function getStatus(): string
    {
        return $this->status;
    }

    public function getRegisteredAt(): \DateTime
    {
        return $this->registeredAt;
    }

    public function getActivatedAt(): ?\DateTime
    {
        return $this->activatedAt;
    }

    /**
     * @throws \RuntimeException
     */
    public function activate(UserActivationToken $token, string $timestamp = 'now'): void
    {
        if ($this->activatedAt) {
            throw new \RuntimeException('User already activated!');
        }

        $token->consume($this);

        $this->status = self::ENABLED;
        $this->activatedAt = new \DateTime($timestamp);
    }

    public function update(Registration $registration): void
    {
        $this->email = $registration->getEmail();
        $this->firstName = $registration->firstName;
        $this->lastName = $registration->lastName;
        $this->gender = $registration->gender;
        $this->birthdate = $registration->getBirthdate();

        $address = $registration->getPostAddress();

        if (!$this->postAddress->equals($address)) {
            $this->postAddress = PostAddressEmbeddable::createFromAddress($address);
        }

        $this->office = $registration->getOffice();
    }

    public function isEnabled(): bool
    {
        return $this->status === self::ENABLED;
    }

    public function getLastLoggedAt(): ?\DateTime
    {
        return $this->lastLoggedAt;
    }

    public function recordLastLoggedAt(string $timestamp = 'now'): void
    {
        $this->lastLoggedAt = new \DateTime($timestamp);
    }

    public function getOffice(): ?Office
    {
        return $this->office;
    }

    public function setOffice(?Office $office): void
    {
        $this->office = $office;
    }

    public function equals(self $other): bool
    {
        return $this->id === $other->getId();
    }
}

templates/user/_form.html.twig
{% block user_form %}
    {{ form_start(form) }}

    {{ form_errors(form) }}

    {% if form.email is defined %}
        <fieldset>
            <legend>Access information</legend>
            {% if form.email is defined %}
                {{ form_row(form.email, { label: 'E-mail:' }) }}
            {% endif %}

            {% if form.password is defined %}
                {{ form_row(form.password.first, { label: 'Password:', attr: { placeholder: 'min 6 characters' } }) }}
                {{ form_row(form.password.second, { label: 'Password confirmation:', attr: { placeholder: 're-enter password' } }) }}
            {% endif %}
        </fieldset>
    {% endif %}

    <fieldset>
        <legend>Personal information</legend>
        {{ form_row(form.firstName, { label: 'First name:' }) }}
        {{ form_row(form.lastName, { label: 'Last name:' }) }}
        {{ form_row(form.gender, { label: 'Gender:' }) }}
        {{ form_row(form.birthdate, { label: 'Birthdate:' }) }}
    </fieldset>

    <fieldset>
        <legend>Address information</legend>
        {{ form_row(form.postAddress.country, { label: 'Country:', attr: { class: 'searchable' } }) }}
        {{ form_row(form.postAddress.city, { label: 'City:' }) }}
        {{ form_row(form.postAddress.address, { label: 'Address:' }) }}
        {{ form_row(form.postAddress.zipCode, { label: 'ZIP code:' }) }}
    </fieldset>

    <fieldset>
        <legend>Work office information</legend>
        {{ form_row(form.office, { label: 'Office:', attr: { class: 'searchable' } }) }}
    </fieldset>

    {% if form.conditions is defined %}
        {{ form_row(form.conditions, { label: 'I accept Terms & Conditions' }) }}
    {% endif %}

    {% if recaptcha_public_key is not empty %}
        {% for flashMessage in app.flashes('error_recaptcha') %}
            <p>{{ flashMessage }}</p>
        {% endfor %}
        <div class="form-group">
            <div class="col-sm-10 col-sm-offset-2">
                <div class="g-recaptcha" data-sitekey="{{ recaptcha_public_key }}"></div>
            </div>
        </div>
    {% elseif app.debug %}
        <input type="hidden" name="g-recaptcha-response" value="fake"/>
    {% endif %}

    <div class="text-center">
        {{ form_widget(form.submit, { attr: { class: 'btn-primary' } }) }}
    </div>

    {{ form_end(form) }}
{% endblock %}

templates/user/home.html.twig
{% extends 'base.html.twig' %}

{% block page_title 'My profile' %}

{% block content %}
    <h4>{{ user.fullName }}</h4>

    <div><strong>E-mail:</strong> {{ user.email }}</div>
    <div><strong>Gender:</strong> {{ user.gender == 'male' ? 'Male' : 'Female' }}</div>
    <div><strong>Birthdate:</strong> {{ user.birthdate|date('d.m.Y') }} (age: {{ user.age }})</div>
    <div><strong>Address:</strong> {{ user.country }}, {{ user.city }} {{ user.address }} {{ user.zipCode }}</div>
    <div><strong>Work office:</strong> {{ user.office == null ? '---' : user.office.fullName }}</div>
    <div><em>User since {{ user.activatedAt|date('d.m.Y H:i:s') }}</em></div>

    <div class="actions">
        <a href="{{ path('user_edit') }}" class="btn btn-default">Edit profile</a>
    </div>
{% endblock %}

templates/user/homepage.html.twig
{% extends 'base.html.twig' %}

{% block content %}
    <h2>My profile</h2>

    <div>
        <span>{{ app.user.fullname }}</span>
        <span>({{ app.user.email }})</span>
    </div>

    <div>User since {{ app.user.activatedAt|date() }}.</div>

    <a href="{{ path('user_edit') }}" class="btn btn-default">Edit profile</a>
{% endblock %}

templates/user/profile.html.twig
{% extends 'base.html.twig' %}

{% use 'user/_form.html.twig' %}

{% block content %}
    <h2>Edit profile</h2>

    {{ block('user_form') }}
{% endblock %}

templates/user/register.html.twig
{% extends 'base.html.twig' %}

{% use 'user/_form.html.twig' %}

{% block title 'Register' %}

{% block javascripts %}
    <script src="https://www.google.com/recaptcha/api.js"></script>
{% endblock %}

{% block content %}
    <main class="col-sm-8">
        {{ block('user_form') }}
    </main>
{% endblock %}